# Generated by Django 3.1.5 on 2021-07-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210711_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='add_bio',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
