# Generated by Django 3.1.5 on 2021-07-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_add_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
